### PR TITLE
chore: bump react-colyseus deps

### PR DESCRIPTION
**Pull request by matthova**

### CODE REVIEW

**Review by JustinBeckwith — APPROVED** [review]

**Comment by matthova** [comment]
@JustinBeckwith even though CI is working it looks like things in this PR are borked until we update vite as well. There's a weird dep issue with httpie which is resolved with the latest vite version

**Comment by JustinBeckwith** [comment]
this is why I don't merge other folks PRs 😆  I'm curious why CI didn't capture the problem?

**Comment by MatthewSH** [comment]
Just an FYI for this, updating colyseus has multiple breaking changes. I encountered this in my own project based on Discord's example. It may require a bit of a refactor on the example for it to work properly. 
The changelogs from Colyseus are basically non-existent about it and very frustrating to figure out what changed and why it broke.

**Comment by matthova** [comment]
> Just an FYI for this, updating colyseus has multiple breaking changes. I encountered this in my own project based on Discord's example. It may require a bit of a refactor on the example for it to work properly. The changelogs from Colyseus are basically non-existent about it and very frustrating to figure out what changed and why it broke.

Thanks for the heads up. @MatthewSH do you have a working example we could reference?

**Comment by MatthewSH** [comment]
> > Just an FYI for this, updating colyseus has multiple breaking changes. I encountered this in my own project based on Discord's example. It may require a bit of a refactor on the example for it to work properly. The changelogs from Colyseus are basically non-existent about it and very frustrating to figure out what changed and why it broke.
> 
> Thanks for the heads up. @MatthewSH do you have a working example we could reference?

I do not have a public one at the moment @matthova. I also rewrote the example using Colyseus's example of using like the `app.config.ts` and letting them handle setting up express so a bit more "hands-off" then the example provided here. 

To be honest, I've been itchin' to rewrite the example anyway using fully upgraded deps and some deployment examples.

**Pull request merged**
